# Generated by Django 2.2.18 on 2024-02-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):


    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('stock_status', models.CharField(blank=True, max_length=20)),
                ('available_stock', models.IntegerField(default=0)),
            ],
        ),
    ]
